apiVersion: v1
kind: Service
metadata:
  name: goweb-metrics
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8033"
spec:
  type: ClusterIP
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: goweb-metrics